apiVersion: v1
kind: Service
metadata:
  name: alive-backend
  namespace: default
  labels:
    app: alive-backend
spec:
  type: ClusterIP
  selector:
    app: alive-deployment
  ports:
    - name: http
      port: 80
      targetPort: 8080
